# -*- coding: utf-8 -*-
"""Sonar rock vs Mine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjILfO9IWXTSrauDLPGNZal4MZ2Dudn8
"""

# Commented out IPython magic to ensure Python compatibility.
# import depedencies 
import pandas as pd 
import numpy as np
import seaborn as sns 
from matplotlib import pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# %matplotlib inline

#load dataset
dataset = pd.read_csv('/content/Copy of sonar data.csv',header=None)

# print first five rows on dataset 
dataset.head()

# check any missing value 
dataset.isnull().sum()

# check shape of the data 
dataset.shape

# get more  information 
dataset.describe(include ='all')

# check type of columns in dataset
dataset.dtypes

#check info 
dataset.info()

X = dataset.drop(columns = [60])

Y = dataset[60]

print(X)

print(Y)

# split data into training and testing 
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.1,random_state=1)

model = LogisticRegression()

# fit the model 
model.fit(X_train,Y_train)

# predict the model
train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

print(X.shape,train_predict.shape,test_predict.shape)

# check the score of model
accuracy_score(Y_train,train_predict)

accuracy_score(Y_test,test_predict)

input_data = [0.0131,0.0201,0.0045,0.0217,0.0230,0.0481,0.0742,0.0333,0.1369,0.2079,0.2295,0.1990,0.1184,0.1891,0.2949,0.5343,0.6850,0.7923,0.8220,0.7290,0.7352,0.7918,0.8057,0.4898,0.1934,0.2924,0.6255,0.8546,0.8966,0.7821,0.5168,0.4840,0.4038,0.3411,0.2849,0.2353,0.2699,0.4442,0.4323,0.3314,0.1195,0.1669,0.3702,0.3072,0.0945,0.1545,0.1394,0.0772,0.0615,0.0230,0.0111,0.0168,0.0086,0.0045,0.0062,0.0065,0.0030,0.0066,0.0029,0.0053]
in_array_data = np.array(input_data)
reshape_data = in_array_data.reshape(1,-1)
prediction = model.predict(reshape_data)
if prediction[0]=='R':
  print('It is a Rock')
else:
  print('It is a Mine')

